apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=ankit123
- name: drupal-db-user
  literals:
  - password=ankitkumar
- name: mysql-userpass
  literals:
  - password=ankitoist
resources:
  - mysql-deployment.yml
  - drupal-deployment.yml