apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: ankitsc1
provisioner: kubernetes.io/aws-ebs
parameters: 
  type: gp2
reclaimPolicy: Retain